version: "3.8"

services:
  node-restapp:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "4000:80"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: on-failure
    env_file:
      - mongodb.env
    ports:
      - "27017:27017"
    # volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # once we need to import some data